// Movies
let
    // Load the CSV file
    Source = Csv.Document(File.Contents("D:\GITHUB\Excel\POWER QUERY\GoodlyPQ\1.Power Query Tricks n Tips\Movies.csv"), [Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
    
    // Promote the first row to headers
    Custom1 = Table.PromoteHeaders(Source),
    
    // Replace "#N/A" with null in specified columns
    #"Replaced Value" = Table.ReplaceValue(Custom1, "#N/A", null, Replacer.ReplaceValue, {"movie_id", "title", "industry", "release_year", "imdb_rating", "studio", "language_id", "budget", "revenue", "unit", "currency"}),
    
    // Filter out rows where "unit" is null
    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each ([unit] <> null)),
    
    // Change the data types of specified columns
    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows", {
        {"movie_id", Int64.Type}, {"title", type text}, {"industry", type text}, 
        {"release_year", Int64.Type}, {"imdb_rating", type text}, 
        {"studio", type text}, {"language_id", Int64.Type}, 
        {"budget", type number}, {"revenue", type number}, 
        {"unit", type text}, {"currency", type text}
    }),
    
    // Add a custom column "BudgetMln" with conditional logic
    #"Added Custom" = Table.AddColumn(#"Changed Type", "BudgetMln", each 
        if [currency] = "USD" 
        then if [unit] = "Billions" then [budget] * 1000 else [budget] * 82 
        else if [unit] = "Billions" then [budget] * 1000 else [budget]),
    
    // Add a custom column "RevenueMln" with conditional logic
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "RevenueMln", each 
        if [currency] = "USD"
        then if [unit] = "Billions" then [revenue] * 1000 else [revenue] * 82
        else if [unit] = "Billions" then [revenue] * 1000 else [revenue]),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom1",{"language_id", "budget", "revenue", "unit", "currency"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"movie_id", Int64.Type}, {"title", type text}, {"industry", type text}, {"release_year", Int64.Type}, {"imdb_rating", type text}, {"studio", type text}, {"BudgetMln", type number}, {"RevenueMln", type number}})
in
    #"Changed Type1"